name: CGI-Lite-Request
version: 0.02
abstract: Request class for CGI::Lite
author: Richard Hundt <richard NO SPAM AT protea-systems.com>
license: artistic
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.6.1
  File::Spec: File::Type
  File::Copy: CGI::Lite
  IO::File: HTTP::Headers
  URI: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
